# Generated by Django 3.2.22 on 2023-10-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20231029_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_shoppingbag',
        ),
    ]
